# Generated by Django 3.0.7 on 2021-03-16 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player3key',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player4key',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='attacks',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='num',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='private_troops',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='public_troops',
        ),
        migrations.AddField(
            model_name='territory',
            name='i',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='territory',
            name='j',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_ready',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='territory',
            name='owner',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Attack',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexgame.Game'),
        ),
    ]
