# Generated by Django 3.0.7 on 2021-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0002_auto_20210315_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_ready',
            field=models.CharField(default='', max_length=50),
        ),
    ]
