# Generated by Django 3.0.7 on 2021-03-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0003_auto_20210315_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.IntegerField(default=-1),
        ),
    ]
