# Generated by Django 3.0.7 on 2021-03-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0005_auto_20210318_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hexgame.Game'),
            preserve_default=False,
        ),
    ]
