# Generated by Django 3.0.7 on 2021-03-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0006_border_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexgame.Player'),
        ),
    ]
