# Generated by Django 3.0.7 on 2021-03-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0007_auto_20210318_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='border',
            old_name='defense',
            new_name='defend',
        ),
    ]
