# Generated by Django 3.0.7 on 2021-03-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0008_auto_20210319_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='available_troops',
        ),
        migrations.CreateModel(
            name='TroopCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_available', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='hexgame.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='hexgame.Player')),
            ],
        ),
    ]
