# Generated by Django 3.0.7 on 2021-03-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0009_auto_20210320_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='troopcounter',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hexgame.Game'),
            preserve_default=False,
        ),
    ]
