# Generated by Django 3.0.7 on 2021-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0011_auto_20210321_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='terrain',
            field=models.IntegerField(default=0),
        ),
    ]
