# Generated by Django 3.0.7 on 2021-03-22 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0012_territory_terrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hexgame.Player'),
        ),
    ]
