# Generated by Django 3.0.7 on 2021-04-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0014_gamefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='territory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='troopcounter',
            name='game',
        ),
        migrations.RemoveField(
            model_name='troopcounter',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='troopcounter',
            name='player',
        ),
        migrations.AddField(
            model_name='gamefile',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Border',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Territory',
        ),
        migrations.DeleteModel(
            name='TroopCounter',
        ),
    ]
