# Generated by Django 3.0.7 on 2021-05-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexgame', '0015_auto_20210422_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickplayCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(default=0)),
            ],
        ),
    ]
